name = "mps-lab"
compatibility_date = "2026-06-07"
pages_build_output_dir = "dist-lab"

[[d1_databases]]
binding = "DB"
database_name = "mps-user-logs"
database_id = "84a081ff-752b-4cdd-8d05-661903fb22bb"
